
globals:
    project_home: $REQ_HOME
    service_module: rq_services
    filter_module: rq_filters    

service_objects:

  infra:
    class: InfraLookupService
    init_params:
      - name: infra_datafile
        value: data/infra_setup.json

  s3:
    class: S3Service
    init_params:  
      - name: region
        value: us-east-1

      - name: local_temp_path
        value: temp_data

      - name: auth_method
        value: basic

      - name: aws_key_id
        value: $AWS_KEY_ID

      - name: aws_secret_key
        value: $AWS_SECRET_KEY

  postgres:
    class: PostgreSQLService
    init_params:
      - name: host
        value: localhost
  
      - name: port
        value: 15433
  
      - name: dbname
        value: reqdb

      - name: schema
        value: public
  
      - name: username
        value: reqdba
  
      - name: password
        value: $REQ_DBA_PASSWORD

      - name: connect_timeout
        value: 5

setups:
  test:     
      filter_func: filter_manifest_records
      file_target: existing_records.jsonl
      mode: accept
